server:
  port: 6789
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: efuavCloud
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ef_cloud?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 60000

  redis:
    host: localhost
    port: 6379
    database: 0
    username: # 如果启用
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

jwt:
  issuer: EFUAV
  subject: EfuavCloudApi
  secret: EfuavCloudApi
  age: 86400

mqtt:
  # @see com.efuav.component.mqtt.model.MqttUseEnum
  # BASIC参数是必需的。
  BASIC:
    protocol: MQTT
    host: 1.14.109.186
    port: 8613
    username: JavaServer
    password: JavaServer
    client-id: 123456
    # 如果协议是ws/wss，则需要此值。
    path:
  DRC:
    protocol: WS
    host: Please enter your ip.
    port: 8083
    path: /mqtt
    username: JavaServer
    password: 123456

cloud-sdk:
  mqtt:
    # 最初连接到mqtt时需要订阅的主题，多个主题用“，”分隔。
    inbound-topic: sys/product/+/status,thing/product/+/requests

url:
  manage:
    prefix: manage
    version: /api/v1
  map:
    prefix: map
    version: /api/v1
  media:
    prefix: media
    version: /api/v1
  wayline:
    prefix: wayline
    version: /api/v1
  storage:
    prefix: storage
    version: /api/v1
  control:
    prefix: control
    version: /api/v1

# Tutorial: https://www.alibabacloud.com/help/en/object-storage-service/latest/use-a-temporary-credential-provided-by-sts-to-access-oss
oss:
  enable: false
  provider: ALIYUN # @see com.efuav.component.OssConfiguration.model.enums.OssTypeEnum
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  access-key: Please enter your access key.
  secret-key: Please enter your secret key.
  expire: 3600
  region: Please enter your oss region. # cn-hangzhou
  role-session-name: cloudApi
  role-arn: Please enter your role arn. # acs:ram::123456789:role/stsrole
  bucket: Please enter your bucket name.
  object-dir-prefix: Please enter a folder name.

#oss:
#  enable: true
#  provider: aws
#  endpoint: https://s3.us-east-1.amazonaws.com
#  access-key:
#  secret-key:
#  expire: 3600
#  region: us-east-1
#  role-session-name: cloudApi
#  role-arn:
#  bucket: cloudapi-bucket
#  object-dir-prefix: wayline

#oss:
#  enable: true
#  provider: minio
#  endpoint: http://192.168.1.1:9000
#  access-key: minioadmin
#  secret-key: minioadmin
#  bucket: cloud-bucket
#  expire: 3600
#  region: us-east-1
#  object-dir-prefix: wayline

logging:
  level:
    com.efuav: debug
  file:
    name: logs/efuav-cloud.log

ntp:
  server:
    host: Google.mzr.me

# 要为应用程序创建许可证
cloud-api:
  app:
    id: 145020
    key: aa2a63200fda079589b5972964cada7
    license: lbDAFnqHrCyKGmF5YpSEkITmpGPBM+dT5iCvO96Kbj3fbLRTwkt///faOkwVzFDnoY+bnJ8kV607AzbS/QCaqDCDOy5loDC8nYVWES9M0wJuyX+LifTuFGL3HvDNVcjlmT+/46Bm+GSjm/nS0brs/9qzDHd9BJ8GR1Fx7VgyOSI=

#livestream:
#  url:
#    # 建议使用程序创建Token。 https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/java/src/main/java/io/agora/media/RtcTokenBuilder2.java
#    agora:
#      channel: Please enter the agora channel.
#      token: Please enter the agora temporary token.
#      uid:  654321
#
#    # RTMP  Note: 此IP是流式传输服务器的地址。如果你想在网页上看到直播，你需要将RTMP流转换为WebRTC流。
#    rtmp:
#      url: Please enter the rtmp access address.  # Example: 'rtmp://192.168.1.1/live/'
#    rtsp:
#      username: Please enter the username.
#      password: Please enter the password.
#      port: 8554
#
#    # GB28181 Note:If you don't know what these parameters mean, you can go to Pilot2 and select the GB28181 page in the cloud platform. Where the parameters same as these parameters.
#    gb28181:
#      serverIP: Please enter the server ip.
#      serverPort: Please enter the server port.
#      serverID: Please enter the server id.
#      agentID: Please enter the agent id.
#      agentPassword: Please enter the agent password.
#      localPort: Please enter the local port.
#      channel: Please enter the channel.
#
#    # Webrtc: Only supports using whip standard
#    whip:
#      url: Please enter the rtmp access address. #  Example：http://192.168.1.1:1985/rtc/v1/whip/?app=live&stream=