server:
  port: 6798
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: efuavCloud
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/ef_cloud?useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/ef_cloud?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 60000

  redis:
    host: localhost
    port: 6379
    database: 0
    username: # 如果启用
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

jwt:
  issuer: EFUAV
  subject: EfuavCloudApi
  secret: EfuavCloudApi
  age: 86400

mqtt:
  # @see com.efuav.component.mqtt.model.MqttUseEnum
  # BASIC参数是必需的。
  BASIC:
    protocol: MQTT
    host: 1.14.109.186
    port: 8613
    username: JavaServer
    password: JavaServer
    client-id: 123456
    # 如果协议是ws/wss，则需要此值。
    path:
  DRC:
    protocol: WS
    host: 1.14.109.186
    port: 8083
    path: /mqtt
    username: JavaServer
    password: 123456

cloud-sdk:
  mqtt:
    # 最初连接到mqtt时需要订阅的主题，多个主题用“，”分隔。
    inbound-topic: sys/product/+/status,thing/product/+/requests

url:
  manage:
    prefix: manage
    version: /api/v1
  map:
    prefix: map
    version: /api/v1
  media:
    prefix: media
    version: /api/v1
  wayline:
    prefix: wayline
    version: /api/v1
  storage:
    prefix: storage
    version: /api/v1
  control:
    prefix: control
    version: /api/v1

oss:
  enable: true
  provider: minio
  endpoint: http://192.168.10.108:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: efuav
  expire: 3600
  region: us-east-1
  object-dir-prefix: wayline

logging:
  level:
    com.efuav: DEBUG
  file:
    name: logs/efuav-cloud.log


#BasePath：/data/efuav/CloudSystem/resources/
BasePath: C://efuav/CloudSystem/

ntp:
  server:
    host: Google.mzr.me

# 要为应用程序创建许可证
cloud-api:
  app:
    id: 145020
    key: aa2a63200fda079589b5972964cada7
    license: lbDAFnqHrCyKGmF5YpSEkITmpGPBM+dT5iCvO96Kbj3fbLRTwkt///faOkwVzFDnoY+bnJ8kV607AzbS/QCaqDCDOy5loDC8nYVWES9M0wJuyX+LifTuFGL3HvDNVcjlmT+/46Bm+GSjm/nS0brs/9qzDHd9BJ8GR1Fx7VgyOSI=
# 大疆智图API
djiTerraAPI:
  app-key: G4Qf5q21tLyj149ciIl0R
  secret-key: 5herHWoFtJDSnwMEaIviAjQ82mypcZmf

livestream:
  url:
    rtmp:
      url: rtmp://efuav.top/djicloud/dji001?txSecret=e090980a7ce88a033cada1eaae4db75f&txTime=6811BEC4
    # It is recommended to use a program to create Token. https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/java/src/main/java/io/agora/media/RtcTokenBuilder2.java
    #    agora:
    #      channel: efcloud
    #      token: dbIk94XfWWmlCBF/+9OE/x1cfN8zYtVmX52KfAYGBgkJJilGhgYZSaZmKcbG5pkpqUlpKSmmZonmxkamZ2olM+rSGQkUHldx0rIwMEgvjsDKlpyTn5pSkMDABOVh+e
    #      uid: 654321

